CREATE TYPE CATEGORY AS ENUM ('HEALTH', 'EDUCATION', 'FINANCE');
CREATE TYPE FREQUENCY_UNIT AS ENUM ('DAILY', 'WEEKLY', 'MONTHLY');
CREATE TYPE STATUS AS ENUM ('IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'FAILED');