CREATE TABLE IF NOT EXISTS GOAL (
    id                  BIGINT PRIMARY KEY AUTO_INCREMENT,
    GOAL_NAME           VARCHAR(128) NOT NULL,
    DESCRIPTION         VARCHAR(1000),
    GOAL_CATEGORY       ENUM ('HEALTH', 'EDUCATION', 'FINANCE'),
    START_DATE          DATE NOT NULL,
    END_DATE            DATE
);