CREATE TABLE IF NOT EXISTS HABIT (
    id              BIGINT PRIMARY KEY AUTO_INCREMENT,
    HABIT_NAME      VARCHAR(128) NOT NULL,
    DESCRIPTION     VARCHAR(1000),
    FREQUENCY       INTEGER,
    FREQUENCY_UNIT  ENUM ('DAILY', 'WEEKLY', 'MONTHLY'),
    goal_id         BIGINT,
    FOREIGN KEY (goal_id) REFERENCES GOAL(id)
);